name: build
run-name: Build and Test ${{ github.ref_name }}

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build, test, and check licenses
        run: mvn verify license:check --batch-mode -DsnapshotDependencyAllowed=true

      - name: Publish test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: '**/target/surefire-reports/*.xml'
