name: Test Mongo

on:
  push:
    paths:
      - 'hawkbit-extension-artifact-repository-mongo/**'
      - 'pom.xml'

jobs:
  test-mongo:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Test hawkbit-extension-artifact-repository-mongo
        run: mvn verify --batch-mode -DsnapshotDependencyAllowed=true -pl hawkbit-extension-artifact-repository-mongo -am

      - name: Publish test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          check_name: Test Results (hawkbit-extension-artifact-repository-mongo)
          files: '**/target/surefire-reports/*.xml'
